Exercise 1: Basic array operations

Import the NumPy library as np.

Create a 1D array of numbers from 0 to 9.

Create a 3×3 NumPy array of all True’s.

Extract all odd numbers from an array of 1-10.

Replace all odd numbers in an array of 1-10 with the value -1 without changing the original array.

In [3]:
import numpy as np

# 2
array = np.arange(10)
print(array)

# 3
bool_arr = np.ones((3,3), dtype=bool)
print(bool_arr)

# 4
odd_values = array[array % 2 == 1]
print(odd_values)

# 5
new_array = array.copy()
new_array[new_array % 2 == 1] = -1
print(new_array)

[0 1 2 3 4 5 6 7 8 9]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[1 3 5 7 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


Exercise 2: Advanced array operations

Convert a 1D array to a 2D array with 2 rows.

Stack two arrays of any size horizontally and vertically.

Get the common items between two Python NumPy arrays.

Remove from one array those items that exist in another. For example, from array a = np.array([1,2,3,4,5]) remove all items that exist in b = np.array([5,6,7,8,9]).

Get the positions where elements of two arrays match. For instance, if array a = np.array([1,2,3,2,3,4,3,4,5,6]) and array b = np.array([7,2,10,2,7,4,9,4,9,8]), find the positions where a and b have the same values.

In [10]:
# 1
array = np.array([1, 2, 3, 4, 5, 6])
new_array = array.reshape(2, -1)
print(new_array)

# 2
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.hstack((a,b)))
print(np.vstack((a,b)))

# 3
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a, b))

# 4
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
print(np.setdiff1d(a, b))

# 5
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.where(a == b))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[2 4]
[1 2 3 4]
(array([1, 3, 5, 7]),)


Exercise 3: Statistics with NumPy

Get the mean, median, standard deviation of a random array of size 30 that has values between 1 and 10.

Normalize a 5x5 random matrix (adjust the values to be between 0 and 1).

Given a 1D array, negate all elements which are between 3 and 8 (both inclusive).

How to round away from zero a float array? For instance, if the array is [-3.1, 2.9, -7.6, 3.6], rounding away from zero would make it [-4, 3, -8, 4].

How to find the most frequent value in an array?

In [13]:
# 1
a = np.random.randint(1, 10, 30)
print(a)
print("Mean: ", np.mean(a))
print("Median: ", np.median(a))
print("Std Dev: ", np.std(a))

# 2
m = np.random.rand(5,5)
norm_m = (m - np.min(m)) / (np.max(m) - np.min(m))
print(norm_m)

# 3
a = np.arange(10)
a[(3 <= a) & (a <= 8)] *= -1
print(a)

# 4
a = np.array([-3.1, 2.9, -7.6, 3.6])
print(np.copysign(np.ceil(np.abs(a)), a))

# 5
a = np.array([1,2,3,1,2,3,1,2,3,3,3,3,4,4,4,4,4])
counts = np.bincount(a)
print(counts)
print(np.argmax(counts))

[2 1 1 3 6 4 5 3 9 1 1 6 8 3 6 9 9 6 7 6 7 6 4 9 1 6 8 6 8 3]
Mean:  5.133333333333334
Median:  6.0
Std Dev:  2.6674998698323407
[[0.74656591 0.2493102  0.6960963  0.66810019 0.27471234]
 [0.89785832 0.82725884 0.96842989 0.35790809 1.        ]
 [0.61787634 0.53904988 0.85615011 0.20606071 0.13522997]
 [0.96826028 0.         0.48715248 0.42894376 0.06672882]
 [0.60821678 0.45895061 0.63828303 0.18626762 0.43123135]]
[ 0  1  2 -3 -4 -5 -6 -7 -8  9]
[-4.  3. -8.  4.]
[0 3 3 6 5]
3


Exercise 4: Linear Algebra with NumPy

Write a function to calculate the Euclidean distance between two points.

Create a 3x3 identity matrix.

Find the determinant of a 4x4 matrix.


In [17]:
# 1
def euclidean_distance(pt1, pt2):
    return np.sqrt(np.sum((np.array(pt1) - np.array(pt2))**2))

print(euclidean_distance([1, 3], [2, 4]))


# 3
identity = np.eye(3)
print(identity)

# 4
a = np.random.rand(4, 4)
print(a)
print(np.linalg.det(a))


1.4142135623730951
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.74018173 0.29167089 0.17240143 0.45338594]
 [0.85641249 0.2589142  0.15084712 0.7002858 ]
 [0.08576302 0.80862277 0.38035398 0.73060266]
 [0.46752692 0.50681711 0.03489261 0.39190809]]
-0.03263525649138307
